version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: cropsense_db
    environment:
      POSTGRES_USER: cropsense_user
      POSTGRES_PASSWORD: cropsense_password
      POSTGRES_DB: cropsense
    ports:
      - "5432:5432"
    volumes:
      - cropsense_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  cropsense_postgres_data:
